spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myusername
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql